name: trading_gpu
channels:
  - conda-forge
  - rapidsai
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.0=h0fbd49f_19
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h149bd38_3
  - aws-c-http=0.10.4=h37a7233_0
  - aws-c-io=0.21.2=h6252d9a_1
  - aws-c-mqtt=0.13.3=h19deb91_3
  - aws-c-s3=0.8.6=h800fcd2_2
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.33.1=hb4fd278_2
  - aws-sdk-cpp=1.11.606=h31ade35_1
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=h4bb41a7_3
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cuda-bindings=12.9.5=py310ha1f8f56_0
  - cuda-cccl_linux-64=12.9.27=ha770c72_0
  - cuda-crt-dev_linux-64=12.9.86=ha770c72_2
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart-dev=12.9.79=h5888daf_0
  - cuda-cudart-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart-static=12.9.79=h5888daf_0
  - cuda-cudart-static_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvcc-dev_linux-64=12.9.86=he91c749_2
  - cuda-nvcc-impl=12.9.86=h85509e4_2
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvvm-dev_linux-64=12.9.86=ha770c72_2
  - cuda-nvvm-impl=12.9.86=h4bc722e_2
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-pathfinder=1.3.3=pyhcf101f3_0
  - cuda-python=12.9.5=pyh698daf1_0
  - cuda-version=12.9=h4f385c5_3
  - cudf=24.10.01=cuda12_py310_241009_g7b0adfa253_0
  - cupy=13.6.0=py310h8c3aed4_2
  - cupy-core=13.6.0=py310hbc0d89f_2
  - dlpack=0.8=h59595ed_3
  - fastrlock=0.8.3=py310h25320af_2
  - fmt=11.0.2=h07f6e7f_1
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - icu=78.1=h33c6efd_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=17.0.0=h31cdc9f_71_cpu
  - libarrow-acero=17.0.0=h635bf11_71_cpu
  - libarrow-dataset=17.0.0=h635bf11_71_cpu
  - libarrow-substrait=17.0.0=h3f74fd7_71_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h676940d_1
  - libcudf=24.10.01=cuda12_241009_g7b0adfa253_0
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcufile-dev=1.14.1.1=hecca717_1
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.17.0=h4e3cde8_1
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libkvikio=24.10.00=cuda12_241009_g85a88a2_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.9.86=hecca717_2
  - libnvptxcompiler-dev=12.9.86=ha770c72_2
  - libnvptxcompiler-dev_linux-64=12.9.86=ha770c72_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libparquet=17.0.0=h790f06f_71_cpu
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - librmm=24.10.00=cuda12_241009_g3223f841_0
  - libsqlite=3.51.1=hf4e2dac_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libthrift=0.22.0=h454ac66_1
  - libudev1=258.3=h6569c3e_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.46.0=py310hee1c697_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numba=0.63.1=py310h225f558_0
  - numpy=2.2.6=py310hefbff90_0
  - nvcomp=4.0.1=hbc370b7_0
  - nvtx=0.2.14=py310h7c4b9e2_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.1.3=h61e0c1e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.2=py310hf9f9076_1
  - pip=25.3=pyh8b19718_0
  - pyarrow=17.0.0=py310hb7f781d_2
  - pyarrow-core=17.0.0=py310hac404ae_2_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylibcudf=24.10.01=cuda12_py310_241009_g7b0adfa253_0
  - pynvjitlink=0.7.0=12.9_py310_250625_3693c9cd_hd6618c4
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - rdma-core=60.0=hecca717_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - rich=14.2.0=pyhcf101f3_0
  - rmm=24.10.00=cuda12_py310_241009_g3223f841_0
  - s2n=1.5.23=h8e187f5_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - spdlog=1.14.1=hed91bc2_1
  - tk=8.6.13=noxft_ha0e22de_103
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6

prefix: "/home/sethm/miniforge3/envs/trading_gpu"
